# Generated by Django 5.0.2 on 2024-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="accounts",
            field=models.ManyToManyField(blank=True, to="trees.account"),
        ),
    ]
