# Generated by Django 5.0.2 on 2024-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_alter_user_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="users",
            field=models.ManyToManyField(blank=True, to="trees.user"),
        ),
    ]
