# Generated by Django 5.0.2 on 2024-02-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0003_alter_account_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantedtree",
            name="age",
        ),
    ]
